language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t yimialmonte/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yimialmonte/docker-react npm run test